import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  content: {
    flex: 4,
  },
  wordToGuessContainer: {
    borderColor: 'lightgray',
    backgroundColor: 'white',
    borderWidth: 1,
    display: 'flex',
    height: Dimensions.get('window').height / 2.5,
    alignItems: 'center',
    width: '90%',
    justifyContent: 'center',
    padding: 30,
    borderRadius: 20,
    gap: 20,
  },
  increase: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  progressBar: {
    height: 3,
    backgroundColor: 'coral',
    width: '80%',
  },
  increaseText: {
    height: 25,
    width: '10%',
    borderColor: 'coral',
    borderWidth: 2,
    borderRadius: 100,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  increaseTextIos: {
    height: 30,
    width: '10%',
    borderColor: 'coral',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  englishWord: {
    color: 'dimgray',
    fontWeight: '500',
    fontSize: 24,
  },
  input: {
    width: '90%',
    height: 40,
    borderWidth: 1,
    borderColor: 'lightgray',
    borderRadius: 7,
    color: 'dimgray',
  },
  button: {
    padding: 8,
    width: 90,
    backgroundColor: 'coral',
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
  },
  badAnswer: {
    padding: 10,
    textAlign: 'center',
    backgroundColor: 'darkslategrey',
    marginTop: 10,
    borderRadius: 20,
    alignSelf: 'center',
  },
});

export default styles;
